### ISSUE TITLE
versioning and/or tag 

### ISSUE THREAD

**Issue by ThomasSaout** [ciaranm/glasgow-subgraph-solver#18]
I'm currently a PhD student, working under the CIFRE (French co-financing program). I'm developing a solution that uses your solver, but with the current change I need to review my deployment procedure. Could you put a version tag in this repo to avoid this problem in the future?  

Thank you in advance

**Comment by ciaranm** [comment]
Was it the switch to CMake that caused problems? Part of the reason I did that was to make integration into other projects somewhat easier, so hopefully this kind of thing won't happen so much in the future. This is also why I've started moving headers into separate directories -- I still need to move them into namespaces, and convert to more modern C++, so there's probably at least one more round of breakage to go in the short term.

Can you tell me which parts of the API you're using, and want to be stable? I don't know the details of how people are using the solver, so I'm not sure which parts I should try to keep unchanged.

**Comment by ciaranm** [comment]
Ah OK. If you're just calling the binaries, I'm probably done breaking things for you for the foreseeable future. I'm currently trying to tidy things up a bit to get us to the point we can have a first stable release. I would recommend trying to update to using the new build system if you can. I'll try to remember to tag something before I start any future major changes (e.g. to the output format).

**Comment by ciaranm** [comment]
PS if you've not seen this, https://mcfelix.me/project/glyphgraph/ might be of interest. A while ago we tried something similar with using graphs for OCR and couldn't get it to work, but that doesn't mean it's not feasible, just that the way we tried wasn't the right one...

**Comment by ThomasSaout** [comment]
It's really interesting work but it's my words that lead you to a misunderstanding. I don't do OCR, but I use a professional OCR model to extract the characters, organise them into words or sentences, and there words are the vertices of the graph representation.

I can't share my work now, because of the publication process, but if you want it when it's finished I can send it to you, it's clearly easier to understand with diagrams and if it helps you show use cases for your solver.

Best regards

**Comment by ciaranm** [comment]
Thanks, I'd be very interested to see what you're doing when it's ready.
