### ISSUE TITLE
build without thread

### ISSUE THREAD

**Issue by ShunyangLi** [ciaranm/glasgow-subgraph-solver#9]
Hi,

Is that possible to build the code without using threads?

Best

**Comment by ciaranm** [comment]
Probably not: we use threads for timeouts, not just for parallel search. Can I ask why you'd need to do this? Threads are a core C++ language feature these days.

**Comment by ShunyangLi** [comment]
Hi ciaranm,

I can not install boost libraries to enable threads since I do not have sudo permission. I tried to download boost libraries in the local machine, but it still get some errors.

Best,
